# -*- coding: utf-8 -*-
"""Feb26_Rag_Session_FullScript_UI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yXDMGAyEQN4yiFG3lp9JHbjHPDz-WXa8
"""

# ============================================================
# PDF or URL -> Chunks -> FAISS -> RAG Chat (OpenRouter)
# Gradio UI + OpenRouter key input + Wikipedia table support
# ============================================================

!pip -q install -U gradio requests beautifulsoup4 pandas lxml \
  pypdf langchain langchain-community langchain-openai langchain-text-splitters faiss-cpu

import os
import re
import requests
import pandas as pd
from bs4 import BeautifulSoup

import gradio as gr

from pypdf import PdfReader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_core.documents import Document

DEFAULT_HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36"
}

STATE = {"vectorstore": None, "source": None, "chunks": 0}

# -------------------------------
# Utilities
# -------------------------------
def normalize_whitespace(text: str) -> str:
    if not text:
        return ""
    text = text.replace("\xa0", " ")
    text = re.sub(r"\s+", " ", text).strip()
    return text

def require_key(openrouter_key: str) -> str:
    if not openrouter_key or not openrouter_key.strip():
        raise ValueError("Missing OpenRouter API Key. Paste it in the UI.")
    return openrouter_key.strip()

def make_embeddings(openrouter_key: str, embedding_model: str):
    return OpenAIEmbeddings(
        model=embedding_model,
        base_url="https://openrouter.ai/api/v1",
        api_key=openrouter_key,
    )

def make_llm(openrouter_key: str, chat_model: str, temperature: float):
    return ChatOpenAI(
        model=chat_model,
        base_url="https://openrouter.ai/api/v1",
        api_key=openrouter_key,
        temperature=temperature,
    )

# -------------------------------
# Web scraping (with Wikipedia tables)
# -------------------------------
def fetch_clean_text(url: str) -> str:
    r = requests.get(url, headers=DEFAULT_HEADERS, timeout=30)
    r.raise_for_status()
    soup = BeautifulSoup(r.text, "html.parser")

    for tag in soup(["script", "style", "nav", "header", "footer", "noscript", "aside"]):
        tag.decompose()

    main = soup.select_one("#mw-content-text") or soup.select_one("main") or soup.body
    if not main:
        return ""

    paras = main.find_all("p")
    text = "\n".join(p.get_text(" ", strip=True) for p in paras if p.get_text(strip=True))
    if not text.strip():
        text = main.get_text("\n", strip=True)

    return normalize_whitespace(text)

def fetch_wikipedia_tables(url: str) -> str:
    try:
        tables = pd.read_html(url)  # parses HTML tables into DataFrames
        if not tables:
            return ""
        parts = []
        for i, df in enumerate(tables, start=1):
            df = df.copy()
            df.columns = [str(c) for c in df.columns]
            parts.append(f"\n\n=== TABLE {i} ===\n{df.to_csv(index=False)}")
        return "".join(parts).strip()
    except Exception:
        return ""

def build_corpus_from_url(url: str) -> str:
    text = fetch_clean_text(url)
    tables = fetch_wikipedia_tables(url) if "wikipedia.org" in url else ""
    return (text + "\n\n" + tables).strip()

# -------------------------------
# PDF reading
# -------------------------------
def pdf_to_text(pdf_path: str) -> str:
    reader = PdfReader(pdf_path)
    pages = []
    for p in reader.pages:
        t = p.extract_text() or ""
        pages.append(t)
    return normalize_whitespace("\n".join(pages))

def build_corpus_from_pdfs(files) -> tuple[str, list[str]]:
    """
    Gradio file component returns list of temp file objects.
    We return combined corpus + list of filenames.
    """
    if not files:
        return "", []

    texts = []
    names = []
    for f in files:
        path = f.name  # temp path in Colab/Gradio
        names.append(os.path.basename(path))
        t = pdf_to_text(path)
        if t.strip():
            texts.append(f"\n\n=== PDF: {os.path.basename(path)} ===\n{t}")
    return "\n".join(texts).strip(), names

# -------------------------------
# Index building
# -------------------------------
def ui_build_index(url: str, pdf_files, openrouter_key: str,
                   chunk_size: int, chunk_overlap: int, embedding_model: str):
    try:
        openrouter_key = require_key(openrouter_key)

        status = []
        corpus = ""

        # Decide source: PDFs win if provided; otherwise URL
        if pdf_files and len(pdf_files) > 0:
            status.append("Reading PDF(s)...")
            corpus, names = build_corpus_from_pdfs(pdf_files)
            if not corpus:
                return "❌ PDFs loaded but no text extracted (scanned PDFs need OCR)."
            source_label = "PDF: " + ", ".join(names)
        else:
            if not url or not url.strip():
                return "❌ Provide either a Website URL OR upload PDF(s)."
            url = url.strip()
            status.append("Fetching web page...")
            corpus = build_corpus_from_url(url)
            if not corpus:
                return "❌ No text extracted (page may block scraping)."
            source_label = url

        status.append(f"Extracted text length: {len(corpus)} characters")
        status.append("Splitting into chunks...")

        splitter = RecursiveCharacterTextSplitter(
            chunk_size=int(chunk_size),
            chunk_overlap=int(chunk_overlap),
        )
        docs = splitter.create_documents([corpus], metadatas=[{"source": source_label}])
        status.append(f"Chunks created: {len(docs)}")

        status.append("Creating embeddings + building FAISS index...")
        embeddings = make_embeddings(openrouter_key, embedding_model)
        vs = FAISS.from_documents(docs, embeddings)

        STATE["vectorstore"] = vs
        STATE["source"] = source_label
        STATE["chunks"] = len(docs)

        status.append("✅ Index built successfully!")
        status.append(f"Source: {source_label}")
        status.append("Now ask questions below.")
        return "\n".join(status)

    except requests.HTTPError as e:
        return f"❌ Build Index failed: HTTPError: {e}"
    except Exception as e:
        return f"❌ Build Index failed: {type(e).__name__}: {e}"

def ui_clear_index():
    STATE["vectorstore"] = None
    STATE["source"] = None
    STATE["chunks"] = 0
    return "✅ Cleared index."

# -------------------------------
# Ask (RAG)
# -------------------------------
def ui_ask(question: str, openrouter_key: str, top_k: int, temperature: float, chat_model: str):
    try:
        openrouter_key = require_key(openrouter_key)

        if STATE["vectorstore"] is None:
            return "❌ Please build the index first."

        if not question or not question.strip():
            return "❌ Please enter a question."

        vs = STATE["vectorstore"]
        docs = vs.similarity_search(question.strip(), k=int(top_k))
        if not docs:
            return "I couldn't retrieve any relevant text from the index."

        context = "\n\n".join([d.page_content for d in docs])

        llm = make_llm(openrouter_key, chat_model, float(temperature))

        prompt = f"""
You are a helpful assistant.

Use the context below to answer the question.

If the question is:
- asking for a summary
- asking what the document/page is about

Then generate a short summary based on the context.

If the answer truly cannot be inferred from the context, say:
"I don't know based on the provided document."

Context:
{context}

Question: {question}
Answer:
""".strip()

        resp = llm.invoke(prompt)
        answer = resp.content if hasattr(resp, "content") else str(resp)

        retrieved_debug = "\n".join(
            [f"{i+1}) {d.metadata.get('source','')} (chunk chars: {len(d.page_content)}) | preview: {d.page_content[:160]}..."
             for i, d in enumerate(docs)]
        )

        return f"{answer}\n\n---\nRetrieved Top {len(docs)} chunks:\n{retrieved_debug}"

    except Exception as e:
        return f"Ask failed: {type(e).__name__}: {e}"

# -------------------------------
# UI
# -------------------------------
EMBED_MODELS = ["text-embedding-3-small", "text-embedding-3-large"]
CHAT_MODELS = [
    "openai/gpt-4o-mini",
    "openai/gpt-4o",
    "anthropic/claude-3.5-sonnet",
    "google/gemini-1.5-pro",
]

with gr.Blocks(title="PDF/URL → FAISS → RAG Chat (OpenRouter)") as demo:
    gr.Markdown("## 📄 PDF or 🌐 URL → FAISS → RAG Chat (OpenRouter)\nUpload PDF(s) or paste a URL, build FAISS index, then ask questions.")

    with gr.Row():
        url_in = gr.Textbox(label="Website URL (optional if PDF uploaded)", placeholder="Paste a URL (Wikipedia works well)")
        key_in = gr.Textbox(label="OpenRouter API Key", type="password", placeholder="sk-or-v1-...")

    pdf_in = gr.File(label="Upload PDF(s) (optional if URL provided)", file_count="multiple", file_types=[".pdf"])

    with gr.Row():
        build_btn = gr.Button("Build Index", variant="primary")
        clear_btn = gr.Button("Clear Index")

    with gr.Row():
        chunk_size_in = gr.Number(label="Chunk size", value=1000, precision=0)
        chunk_overlap_in = gr.Number(label="Chunk overlap", value=150, precision=0)
        embed_model_in = gr.Dropdown(label="Embeddings model", choices=EMBED_MODELS, value="text-embedding-3-small")

    status_out = gr.Textbox(label="Status", lines=7)

    gr.Markdown("## ❓ Ask Questions")
    question_in = gr.Textbox(label="Question", placeholder="Ask about the PDF/URL content (tables included for Wikipedia)")
    with gr.Row():
        topk_in = gr.Slider(label="Top K chunks", minimum=1, maximum=12, value=6, step=1)
        temp_in = gr.Slider(label="Temperature", minimum=0.0, maximum=1.0, value=0.2, step=0.05)
        chat_model_in = gr.Dropdown(label="Chat model (OpenRouter)", choices=CHAT_MODELS, value="openai/gpt-4o-mini")

    ask_btn = gr.Button("Ask")
    answer_out = gr.Textbox(label="Answer", lines=10)

    build_btn.click(
        fn=ui_build_index,
        inputs=[url_in, pdf_in, key_in, chunk_size_in, chunk_overlap_in, embed_model_in],
        outputs=[status_out],
    )
    clear_btn.click(fn=ui_clear_index, inputs=[], outputs=[status_out])

    ask_btn.click(
        fn=ui_ask,
        inputs=[question_in, key_in, topk_in, temp_in, chat_model_in],
        outputs=[answer_out],
    )

demo.launch(share=True, inbrowser=True)