# -*- coding: utf-8 -*-
"""Feb26_Rag_working_session1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139NeEKK4_nAjXpKP39d0KqK4qvs9qOHc
"""

### 1. Install Required Libraries

## langchain → Orchestration framework for LLM + retrieval
## langchain_community → Loaders like WebBaseLoader
## faiss-cpu → Vector database for similarity search
## langchain-openai → Connect LLM/embeddings
## This sets up your RAG toolkit.

!pip install langchain_community langchainhub faiss-cpu langchain langchain-openai

### 2. Reading API Key from Colab Secrets

## Securely pulls your API key
## Sets it as environment variable
## So LangChain can use it automatically

from google.colab import userdata
import os

openrouter_key = userdata.get("OPENROUTER_API_KEY")  # use exact secret name
os.environ["OPENAI_API_KEY"] = openrouter_key

### 3. Web Scrapping

## Loading the page
## It converts the webpage into a Document object
## docs contains -> page_content (text) and metadata (source URL, title, etc.)

from langchain_community.document_loaders import WebBaseLoader
loader = WebBaseLoader(web_paths=["https://www.cricbuzz.com/profiles/1413/virat-kohli"])
docs = loader.load()
print (docs)

### 4. Split Documents

##LLMs have token limits.
##Instead of giving full webpage, we:
   ##Break into chunks of 1000 characters
   ##With 200 character overlap
   ##Overlap prevents context cutting

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
splits = text_splitter.split_documents(docs)

print(splits[0])
print(splits[1])

print (len(splits))

## The webpage became 50 searchable chunks.
## Perfect for vector storage.

### 5. Add Docs to VectorDB

## OpenAIEmbeddings → converts text into numerical vectors
## FAISS → local vector database for similarity search
## Preparing: Text ➜ Embeddings ➜ Vector Index

from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import FAISS

## This model:
## Takes text chunks
## Converts each chunk into a vector (like a fingerprint)
## Each chunk becomes something like:
## [0.023, -0.892, 0.442, ...]

### 1. Create Embeddings Model
embeddings = OpenAIEmbeddings(
    model="openai/text-embedding-3-small",
    api_key=openrouter_key,
    base_url="https://openrouter.ai/api/v1"
)


### 2. create FAISS vector store

## It sends text → embedding model
## Gets numerical vector
## Stores vector inside FAISS index
vectorstore = FAISS.from_documents(
    documents=splits,
    embedding=embeddings
)

print("FAISS index created successfully")

print("Total vectors:", vectorstore.index.ntotal)
print("Total documents:", len(vectorstore.docstore._dict))
print(vectorstore.index_to_docstore_id)

doc_id = list(vectorstore.index_to_docstore_id.values())[0]

# Get FAISS index position
faiss_index = list(vectorstore.index_to_docstore_id.keys())[0]

# Get embedding vector
embedding = vectorstore.index.reconstruct(faiss_index)

# Get document
doc = vectorstore.docstore.search(doc_id)

print({
    "ids": [doc_id],
    "embeddings": [embedding],
    "documents": [doc.page_content]
})

### Create a Helper Function to display document id, embeddings and documents
def faiss_get(vectorstore, doc_id):
    for idx, stored_id in vectorstore.index_to_docstore_id.items():
        if stored_id == doc_id:
            embedding = vectorstore.index.reconstruct(idx)
            document = vectorstore.docstore.search(doc_id)
            return {
                "ids": [doc_id],
                "embeddings": [embedding],
                "documents": [document.page_content]
            }

### Show me what’s actually stored in the vector database.

# Example usage
first_id = list(vectorstore.index_to_docstore_id.values())[0]
print("\nCollection 1 - ", faiss_get(vectorstore, first_id))

# Example usage
second_id = list(vectorstore.index_to_docstore_id.values())[1]
print("\nCollection 2 - ", faiss_get(vectorstore, second_id))


# Example usage
third_id= list(vectorstore.index_to_docstore_id.values())[2]
print("\nCollection 3 - ", faiss_get(vectorstore, third_id))

### RAG Pipeline

### 6. Retrieval

#Convert question → embedding
#Search FAISS
#Return top-k relevant chunks
#This is the “R” in RAG.

retriever = vectorstore.as_retriever()

### 7. Augumentation

### What is happening here?

### pulling a predefined RAG prompt template from LangSmith Hub.

### This prompt typically looks like:

### Use the following context to answer the question.
     # If you don't know, say you don't know.

    # Context:
    # {context}

    # Question:
    # {question}

### This step is critical.
### This is what prevents hallucination.
### Because the model is explicitly instructed:
### Only use context
### Don’t make up answers
### That is the “A” (Augmentation) in RAG.

from langsmith import Client

client = Client()
prompt = client.pull_prompt("rlm/rag-prompt")

### 8. Setup LLM

#Using GPT-4o-mini via OpenRouter
#Temperature = 0 → deterministic output
#Good for factual RAG

import os
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    model="openai/gpt-4o-mini",          # OpenRouter model name
    base_url="https://openrouter.ai/api/v1",
    temperature=0
)

# quick test
print(llm.invoke("Say hi in 1 line.").content)

from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

### These are used to build the chain manually.

# This function:
# Takes retrieved chunks
# Combines them into one context string
# Feeds into prompt

def format_docs(docs):
  return "\n".join(doc.page_content for doc in docs)

### 9. RAG chain Code

### Retriever
# → Format docs
# → Insert into prompt
# → LLM
# → Output parser

rag_chain = ({"context": retriever | format_docs, "question": RunnablePassthrough()}
             | prompt
             | llm
             | StrOutputParser())

### Test RAG Chain Code
rag_chain.invoke("Who is virat")

rag_chain.invoke("How much the price")

rag_chain.invoke("Any testimonials? and certificates provided?")

rag_chain.invoke("Whats the projects available?")

from langchain_core.runnables import RunnableLambda

def print_prompt(prompt_text):
  print ("Prompt - ",prompt_text)
  return prompt_text

### RAG chain Code
rag_chain_with_prompt = ({"context": retriever | format_docs, "question": RunnablePassthrough()}
             | prompt
             | RunnableLambda(print_prompt)
             | llm
             | StrOutputParser())

rag_chain_with_prompt.invoke("Whats virat highest score")